//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_dbo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client_dbo()
        {
            this.Tb_Order = new HashSet<Tb_Order>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int Orders { get; set; }
        public int In_possession { get; set; }
        public int Damaged { get; set; }
        public int Lost { get; set; }
        public decimal Spent { get; set; }
        public System.DateTime Date_added { get; set; }
        public int Users { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Order> Tb_Order { get; set; }
    }
}
