//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tb_Order
    {
        public int ID { get; set; }
        public string CarModelName { get; set; }
        public string ConditionBefore { get; set; }
        public string ConditionAfter { get; set; }
        public string Statu { get; set; }
        [Display(Name = "Return Date")]
        [Required(ErrorMessage = "Return Date is required.")]
        [DataType(DataType.Date)]
        public System.DateTime ReturnDate { get; set; }
        public decimal DailyPrice { get; set; }
        public int O_Days { get; set; }
        public decimal Total { get; set; }

        [Display(Name = "Pick Up Date")]
        [Required(ErrorMessage = "Pick Up Date is required.")]
        [DataType(DataType.Date)]
        public System.DateTime RentDate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string ImageUrl { get; set; }
        public string Des { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }

        public virtual Client_dbo Client_dbo { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual User User { get; set; }
    }
}
