//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Tb_Order = new HashSet<Tb_Order>();
            this.Admins = new HashSet<Admin>();
        }
    
        public int ID { get; set; }
        public string Model { get; set; }
        public string Registration { get; set; }
        public string Color { get; set; }
        public int Capacity { get; set; }
        public string Fuel_type { get; set; }
        public string Transmission { get; set; }
        public string Des { get; set; }
        public decimal Daily_hired_price { get; set; }
        public string Condition { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime Date_added { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Order> Tb_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admin> Admins { get; set; }
    }
}
